apiVersion: foundry.ai/v1
kind: AgentGraph
metadata:
  name: CIBC Session - Card Shipped Notification
  type: system
  version: 1.0.0
  description: Send multi-channel notification when card is shipped
  tags: [cibc, agent-group-4, session, notification, shipped]

spec:
  state_schema_id: null
  triggers: []
  graph:
    nodes:
      - id: entry
        type: entryPoint
        position: { x: 300, y: 50 }
        data:
          label: Card Shipped Event
          description: G&D reports card shipped

      - id: get_preferences
        type: toolCall
        position: { x: 300, y: 150 }
        data:
          label: Get Communication Preferences
          description: Check customer consent and preferred channels
          tool: func-get-customer-communication-preferences

      - id: prepare_message
        type: process
        position: { x: 300, y: 280 }
        data:
          label: Prepare Notification Message
          description: Generate notification content
          model: gpt-4o-mini
          temperature: 0.5
          prompt: |
            Create card shipped notification message:

            Include:
            - Card type
            - Expected delivery date
            - Tracking number (if available)
            - Activation instructions
            - Customer service contact

            Tone: Professional, reassuring

      - id: send_notification
        type: toolCall
        position: { x: 300, y: 410 }
        data:
          label: Send Multi-Channel Notification
          description: Send via SMS, email, push, in-app
          tool: func-send-notification

      - id: record_notification
        type: process
        position: { x: 300, y: 540 }
        data:
          label: Record Notification
          description: Log notification in case history
          model: gpt-4o-mini
          temperature: 0.3

      - id: end
        type: end
        position: { x: 300, y: 670 }
        data:
          label: Notification Sent

    edges:
      - id: e1
        source: entry
        target: get_preferences

      - id: e2
        source: get_preferences
        target: prepare_message

      - id: e3
        source: prepare_message
        target: send_notification

      - id: e4
        source: send_notification
        target: record_notification

      - id: e5
        source: record_notification
        target: end
