#!/bin/bash

# Install Node.js for Engineering Department Frontend
# This script provides instructions for installing Node.js

echo "🔧 Node.js Installation Required"
echo "================================"
echo ""
echo "Node.js and npm are required to run the frontend."
echo ""
echo "OPTION 1: Install via Homebrew (Recommended)"
echo "---------------------------------------------"
echo "Step 1: Install Homebrew (if not installed):"
echo ""
echo '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
echo ""
echo "Step 2: Install Node.js:"
echo ""
echo "brew install node@20"
echo ""
echo ""
echo "OPTION 2: Direct Download"
echo "--------------------------"
echo "Visit: https://nodejs.org/en/download/"
echo "Download the macOS installer (LTS version)"
echo ""
echo ""
echo "OPTION 3: Using NVM (Node Version Manager)"
echo "-------------------------------------------"
echo "Step 1: Install NVM:"
echo ""
echo 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash'
echo ""
echo "Step 2: Install Node.js:"
echo ""
echo "nvm install 20"
echo "nvm use 20"
echo ""
echo ""
echo "After Installation"
echo "------------------"
echo "Verify installation with:"
echo "  node --version  (should show v20.x.x)"
echo "  npm --version   (should show 10.x.x)"
echo ""
echo "Then return to the Engineering Department directory and run:"
echo "  cd '/Users/nwalker/Development/Projects/Engineering Department/engineeringdepartment'"
echo "  npm install"
echo "  npm run dev"
echo ""
