"""
2ba93536_7bad_48e4_ab2c_130194dc8889 - LangGraph Agent
Auto-generated from Agent Foundry visual designer
Generated by: Agent Foundry Backend Converter
"""

from typing import Dict, Any
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langchain_anthropic import ChatAnthropic
from langgraph.types import interrupt, Command

# Import global AgentState from shared state module
import sys
sys.path.insert(0, "/app")
from agents.state import AgentState

# ============================================
# Agent Class
# ============================================

class Agent2Ba935367Bad48E4Ab2C130194Dc8889Agent:
    """Agent class containing all node handlers"""
    
    def process_process_1763987208129(self, state: AgentState) -> AgentState:
        """
        Agent that talks about books.
        Type: process
        """
        
        # Initialize gpt-5-mini
        llm = ChatOpenAI(
            model="gpt-5-mini",
            temperature=0.7,
            max_tokens=1000,
        )
        
        # System prompt guides the LLM behavior for this specific task
        system_prompt = """Agent that talks about books."""
        
        # Process messages with LLM
        messages = state["messages"]
        if not messages:
            messages = [HumanMessage(content="Start workflow")]
        
        # Prepend SystemMessage with task instructions
        messages = [SystemMessage(content=system_prompt)] + list(messages)
        
        response = llm.invoke(messages)
        
        # Update state with response
        updated_messages = list(state.get("messages", []))
        if response:
            updated_messages.append(AIMessage(content=str(response.content if hasattr(response, "content") else response)))
        
        return {
            "messages": updated_messages,
            "final_response": str(response.content if hasattr(response, "content") else response) if response else ""
        }
    
    
# ============================================
# Graph Construction
# ============================================
# Graph construction is handled by agent_loader.py
# The agent_loader reads the YAML manifest, imports this class,
# and builds the StateGraph with the global AgentState schema.
