apiVersion: engineering-dept/v1
kind: Agent
metadata:
  id: exception-agent
  name: Exception Agent
  version: 1.0.0
  description: Runtime error handling, retries, fallbacks, and circuit breakers
  tags:
    - platform
    - tier-1
    - resilience
    - error-handling
  created: "2025-11-16T00:00:00Z"
  updated: "2025-11-16T00:00:00Z"

spec:
  capabilities:
    - error_handling
    - retry_logic
    - fallback_execution
    - circuit_breaker
    - hitl_escalation
    - dead_letter_queue
    - exponential_backoff

  workflow:
    type: langgraph.StateGraph
    entry_point: execute_with_resilience
    recursion_limit: 10
    nodes:
      - id: execute_with_resilience
        handler: agents.workers.exception_agent.ExceptionAgent.execute_with_resilience
        description: Wrap node execution with full resilience (retries, timeout, fallback)
        next:
          - calculate_backoff
          - execute_fallback
          - escalate_to_human
        timeout_seconds: 120

      - id: calculate_backoff
        handler: agents.workers.exception_agent.ExceptionAgent._calculate_backoff
        description: Calculate exponential backoff delay for retries
        next:
          - execute_with_resilience
        timeout_seconds: 5

      - id: execute_fallback
        handler: agents.workers.exception_agent.ExceptionAgent._execute_with_timeout
        description: Execute fallback function when all retries exhausted
        next:
          - END
        timeout_seconds: 60

      - id: escalate_to_human
        handler: agents.workers.exception_agent.ExceptionAgent._escalate_to_human
        description: Human-in-the-loop escalation for unrecoverable errors
        next:
          - END
        timeout_seconds: 30

  integrations:
    - type: redis
      required: true
      operations:
        - circuit_breaker_state
        - dead_letter_queue

    - type: openai
      required: false
      operations:
        - error_analysis

  resource_limits:
    max_concurrent_tasks: 20
    timeout_seconds: 180
    memory_mb: 512
    max_tokens_per_request: 8000

  observability:
    trace_level: info
    metrics_enabled: true
    metrics_interval_seconds: 30
    log_retention_days: 90
    structured_logging: true

  health_check:
    enabled: true
    interval_seconds: 30
    timeout_seconds: 5
    unhealthy_threshold: 3

  configuration:
    default_max_retries: 3
    default_timeout_seconds: 60
    circuit_breaker_threshold: 5
    circuit_breaker_timeout_seconds: 60
    enable_hitl_by_default: false
    dead_letter_queue_max_size: 1000
    exponential_backoff_base_delay: 1.0
    exponential_backoff_max_delay: 30.0

status:
  phase: production
  state: active
  last_health_check: "2025-11-16T00:00:00Z"
  health_status: healthy
