'use client';

import { Package } from 'lucide-react';
import { Card } from '@/components/ui/card';

export default function ArtifactsPage() {
  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-fg-0">Artifacts</h1>
        <p className="text-fg-2 mt-1">Browse and manage generated artifacts</p>
      </div>

      {/* Empty State */}
      <Card className="p-12">
        <div className="flex flex-col items-center justify-center text-center">
          <Package className="w-20 h-20 text-fg-2 mb-4 opacity-50" />
          <h3 className="text-xl font-semibold text-fg-0 mb-2">No artifacts yet</h3>
          <p className="text-fg-2 max-w-md">
            Artifacts generated by your agents will be stored and displayed here
          </p>
        </div>
      </Card>
    </div>
  );
}
